package org.schemaspy.input.dbms.jdbc;

import org.schemaspy.input.dbms.config.DbmsDriverConfiguration;
import org.schemaspy.input.dbms.exceptions.ConnectionFailure;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.net.URLClassLoader;
import java.sql.Driver;
import java.util.*;
import java.util.stream.Collectors;

public class DriverFactory {

    private DbmsDriverConfiguration dbmsDriverConfiguration;

    public DriverFactory(DbmsDriverConfiguration dbmsDriverConfiguration) {
        this.dbmsDriverConfiguration = dbmsDriverConfiguration;
    }

    public Driver createDriver() {
        Driver driver;
        Set<URI> classpath = getExistingUrls(dbmsDriverConfiguration.getDriverPath());
        if (classpath.isEmpty()) {
            URL url = getClass().getResource(dbmsDriverConfiguration.getDriverPath());
            if (url != null) {
                classpath = getExistingUrls(url.getPath());
            }
        }

        ClassLoader loader = getDriverClassLoader(classpath);

        try {
            driver = (Driver)Class.forName(dbmsDriverConfiguration.getDriverClass(), true, loader).newInstance();
            // have to use deprecated method or we won't see messages generated by older drivers
            // @see DriverManager.setLogStream(PrintStream)
            //TODO implement PrintStream to Logger bridge.
            // setLogStream should only be called once maybe in SpringConfig or Main?
            Objects.requireNonNull(driver);
        } catch (Exception exc) {
            throw new ConnectionFailure(createMessage(dbmsDriverConfiguration.getDriverClass(), dbmsDriverConfiguration.getDriverPath(), classpath), exc);
        }

        return driver;
    }

    private String createMessage(String driverClass, String driverPath, Set<URI> classpath) {
        StringBuilder sb = new StringBuilder()
                .append("Failed to create driver '")
                .append(driverClass)
                .append("' from driverPath '")
                .append(driverPath)
                .append(System.lineSeparator())
                .append("Resulting in classpath:");
        if (classpath.isEmpty()) {
            sb.append("empty").append(System.lineSeparator());
        } else {
            sb.append(System.lineSeparator());
            for (URI uri : classpath) {
                sb.append("\t").append(uri.toString()).append(System.lineSeparator());
            }
        }
        List<String> missingPaths = getMissingPaths(driverPath);
        if (!missingPaths.isEmpty()) {
            sb.append("There were missing paths in driverPath:").append(System.lineSeparator());
            for (String path : missingPaths) {
                sb.append("\t").append(path).append(System.lineSeparator());
            }
            sb
                    .append("Use commandline option '-dp' to specify driver location.")
                    .append(System.lineSeparator())
                    .append("If you need to load sibling jars used '-loadjars'");
        }
        return sb.toString();
    }

    /**
     * Returns a {@link ClassLoader class loader} to use for resolving {@link Driver}s.
     *
     * @param classpath
     * @return
     */
    private ClassLoader getDriverClassLoader(Set<URI> classpath) {
        ClassLoader loader;

        // if a classpath has been specified then use it to find the driver,
        // otherwise use whatever was used to load this class.
        // thanks to Bruno Leonardo Gonalves for this implementation that he
        // used to resolve issues when running under Maven
        if (!classpath.isEmpty()) {
            URL[] urls = classpath.stream().map(uri -> {
                try {
                    return uri.toURL();
                } catch (MalformedURLException e) {
                    return null;
                }
            }).filter(Objects::nonNull).collect(Collectors.toList()).toArray(new URL[classpath.size()]);
            loader = new URLClassLoader(urls);
        } else {
            loader = getClass().getClassLoader();
        }

        return loader;
    }

    /**
     * Returns a list of {@link File}s in <code>path</code> that do not exist.
     * The intent is to aid in diagnosing invalid paths.
     *
     * @param path
     * @return
     */
    private List<String> getMissingPaths(String path) {
        List<String> missingFiles = new ArrayList<>();

        String[] pieces = path.split(File.pathSeparator);
        for (String piece : pieces) {
            if (!new File(piece).exists())
                missingFiles.add(piece);
        }

        return missingFiles;
    }

    /**
     * Returns a list of {@link URL}s in <code>path</code> that point to files that
     * exist.
     *
     * @param path
     * @return
     */
    private Set<URI> getExistingUrls(String path) {
        Set<URI> existingUrls = new HashSet<>();

        String[] pieces = path.split(File.pathSeparator);
        for (String piece : pieces) {
            File file = new File(piece);
            if (file.exists())
                existingUrls.add(file.toURI());
        }

        return existingUrls;
    }
}
