# This file contains the descriptions for the command line arguments declared in the class CommandLineArguments.
help=show general usage and available options
outputDirectory=directory to place the generated output in
dbhelp=Show built-in database types and their required connection parameters
debug=Enable debug logging
sso=Remove requirement for user
nohtml=Skip html generation