#
# see http://schemaspy.org/dbtypes.html
# for configuration / customization details
#

# Extended informix database type to support comments as described in https://github.com/schemaspy/schemaspy/issues/425
extends=informix

selectTableCommentsSql=select t.tabname as table_name, c.comments as comments from systables t,qx_table_comments c where t.tabid = c.tabid and t.owner = :schema

selectColumnCommentsSql=select t.tabname as table_name, c.colname as column_name, qx_column_comments.comments as comments from systables t,syscolumns c,qx_column_comments where t.tabid = qx_column_comments.tabid and c.tabid = t.tabid and c.colno = qx_column_comments.colno and t.owner = :schema 
