name: Docker Push Test

on:
  push:
    branches:
      - npetzall_docker_multi_arch
    paths-ignore:
      - '*.md'
      - 'docs/**'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Build, Test
        run: >
          ./mvnw
          --batch-mode
          --update-snapshots
          --errors
          --show-version
          -P release
          verify
          -Dscm.revision=$GITHUB_SHA
      - name: Upload test output
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: testout
          path: |
            target/testout/
            !target/testout/**/bower/
            !target/testout/**/fonts/
            !target/testout/**/*.js
          retention-days: 7
      - name: Echo
        run: |
          echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "GITHUB_SHA: $GITHUB_SHA"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NP_DOCKER_USER }}
          password: ${{ secrets.NP_DOCKER_TOKEN }}
      - name: Set up QEMU (Docker)
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Buildx Bake(Temurin-snapshot)
        uses: docker/bake-action@v4
        with:
          files: docker-bake.hcl
          push: true
          targets: snapshot
          set: |
            *.cache-to=
