name: Main build

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    if: ${{ github.repository_owner == 'schemaspy' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nelonoel/branch-name@1ea5c86cb559a8c4e623da7f188496208232e49f
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build, Test, Sonar
        run: >
          ./mvnw
          --batch-mode
          --update-snapshots
          --errors
          --show-version
          -P sonar
          -Dsonar.host.url=https://sonarcloud.io
          verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Deploy to Github Packages
        if: success()
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: "${{ github.repository }}:snapshot"
          build-args: |
            GIT_BRANCH=${BRANCH_NAME}
            GIT_REVISION=${{ github.sha }}}
      - name: Inspect
        run: docker inspect ${{ steps.docker_build.outputs.digest }}