name: Npetzall Manual Tests

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release [n.n.n]'
        required: true
        default: "[n.n.n]"
      next_development_version:
        description: 'Next development version [n.n.n]'
        required: true
        default: "[n.n.n+1]"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Inputs
        run: '[[ $RELEASE_VERSION =~ $VERSION_PATTERN ]] && [[ $NEXT_VERSION =~ $VERSION_PATTERN ]]'
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          NEXT_VERSION: ${{ github.event.inputs.next_development_version }}
          VERSION_PATTERN: '^[0-9]+\.[0-9]+\.[0-9]+$'
      - name: Everything is awesome
        if: success()
        run: echo "Everything is actually awesome"