name: Npetzall Manual Tests

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release [n.n.n]'
        required: true
      next_development_version:
        description: 'Next development version [n.n.n]'
        required: true

jobs:
  release:
    if: ${{ github.repository_owner == 'npetzall' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check Inputs
        run: echo "$RELEASE_VERSION > $NEXT_VERSION"
        env:
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          NEXT_VERSION: ${{ github.event.inputs.next_development_version }}
      - name: Everything is awesome
        if: success()
        run: echo "Everything is actually awesome"